apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapi
  labels:
    app: hellokuber
spec:
  replicas: 1
  selector:
    matchLabels:
      service: helloapi
  template:
    metadata:
      labels:
        app: hellokuber
        service: helloapi
    spec:
      containers:
      - name: helloapi
        image: acrglobalnews.azurecr.io/helloapi:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: WebApiBaseAddress
            value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: helloapi
  labels:
    app: hellokuber
    service: helloapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: helloapi
